=== vrsa9208/modulo5Java/src/testXML/esquema2.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="diplomado">
        <xs:complexType>
            <xs:all>
                <xs:element name="modulos" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>                  
                </xs:element>
                <xs:element name="fechaInicio" type="xs:date" />
                <xs:element name="fechaFin" type="xs:date" />
                <xs:element name="instructores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="instructor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="primerApellido" type="xs:string" />
                                        <xs:element name="segundoApellido" type="xs:string" minOccurs="0" />
                                        <xs:choice>
                                            <xs:element name="noCuenta" type="xs:string" />
                                            <xs:element name="cheque" type="xs:boolean" fixed="true" />
                                            <xs:element name="efectivo" type="xs:boolean" fixed="true" />
                                        </xs:choice>
                                    </xs:sequence>
                                    <xs:attribute name="sexo" use="required" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <!--Los atributos por default son opcionales-->
            <!--Se ponen dentro del complexType, pero despuÃ©s del indicador de orden>
            <xs:attribute name="generacion" type="xs:integer" use="required" />
            <xs:attribute name="nombre" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vrsa9208/modulo5Java/build/classes/testXML/esquema2a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<diplomado
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='esquema2.xsd'
    generacion="6"
    nombre="Nombre del diplomado">
    <modulos>
        <modulo></modulo>
        <modulo></modulo>
        <modulo></modulo>
    </modulos>
    <fechaInicio>2015-09-04</fechaInicio>
    <fechaFin>2016-03-12</fechaFin>
    <instructores>
        <instructor sexo="masculino">
            <nombre></nombre>
            <primerApellido></primerApellido>
            <segundoApellido></segundoApellido>
            <noCuenta></noCuenta>
        </instructor>
        <instructor sexo="femenino">
            <nombre></nombre>
            <primerApellido></primerApellido>
            <!--<segundoApellido></segundoApellido>-->
            <cheque>true</cheque>
        </instructor>
        <instructor sexo="masculino">
            <nombre></nombre>
            <primerApellido></primerApellido>
            <segundoApellido></segundoApellido>
            <efectivo>true</efectivo>
        </instructor>
    </instructores>

</diplomado>
